enable: true
interval: 0
workers: 1
verbose: false

sql:
  - name: example-sql-dne
    source: example/src/dne.db
    dest: example/src/dne.backup.db
    enable: true

  - name: example-sql-1
    source: example/src/test.db
    dest: example/src/test.backup.db
    enable: true

rsync:
  - name: example-source-1
    source: example/src/
    dest: example/dest
    options:
      noowner: true
      nogroup: true
      notimes: true
      exclude:
        - "*ignore*"
      delete: true
      deleteduring: true
      deleteexcluded: true
      force: true
    enable: true

  - name: example-dne-1
    source: /srcdne/
    dest: /destdne
    enable: true

  - name: example-disabled-1
    source: /source/
    dest: /dest
    enable: false
