sql:
  - name: sqlexample1
    source: sqlexample1.db
    dest: sqlexample1.db.bak
    options: ''
    priority: 1

  - name: sqlexample2
    source: sqlexample2.db
    dest: sqlexample2.db.bak
    options: ''
    priority: 1

rsync:
  - name: example1
    source: example1Source
    dest: example1Dest
    ignored: '*ignored*'
    options: ''
    priority: 2

  - name: example2
    source: example2Source
    dest: example2Dest
    ignored: '*media*'
    options: option1
    priority: 2