enabled: true

sql:
  - name: sqlexample1
    source: sqlexample1.db
    dest: sqlexample1.db.bak
    options: ''
    enabled: true

  - name: sqlexample2
    source: sqlexample2.db
    dest: sqlexample2.db.bak
    options: ''
    enabled: true

  - name: disabledsqlexample1
    source: disabled.db
    dest: disabled.db.bak
    options: ''

rsync:
  - name: example1
    source: example1Source
    dest: example1Dest
    ignored: '*ignored*'
    options: ''
    enabled: true

  - name: example2
    source: example2Source
    dest: example2Dest
    ignored: '*media*'
    options: option1
    enabled: true
  
test:
  - name: test